//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbnormalQuality
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AbnormalQuality()
        {
            this.AbnormalQualityDetails = new HashSet<AbnormalQualityDetails>();
        }
    
        public System.Guid Id { get; set; }
        public string UnusualNumber { get; set; }
        public System.DateTime MakingTime { get; set; }
        public System.Guid MakingUserId { get; set; }
        public System.Guid ProjectContractId { get; set; }
        public Nullable<System.Guid> EngineeringId { get; set; }
        public Nullable<System.Guid> SupplierTranscationItemId { get; set; }
        public Nullable<System.Guid> ReceiptsId { get; set; }
        public Nullable<System.Guid> ProcessingAtlasId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
    
        public virtual Engineering Engineering { get; set; }
        public virtual ProcessingAtlas ProcessingAtlas { get; set; }
        public virtual ProjectContract ProjectContract { get; set; }
        public virtual Receive Receipts { get; set; }
        public virtual SupplierTranscationItem SupplierTranscationItem { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbnormalQualityDetails> AbnormalQualityDetails { get; set; }
    }
}
