//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbnormalQualityDetails
    {
        public System.Guid Id { get; set; }
        public System.Guid AbnormalQualityId { get; set; }
        public System.Guid ReceiptDetailsId { get; set; }
        public string ProcessingNumber { get; set; }
        public string Specifications { get; set; }
        public int ExceptionsQuantity { get; set; }
        public string ExceptionsReason { get; set; }
        public string ProcessingMethod { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> LossCalculation { get; set; }
        public Nullable<System.Guid> RefundsManufacturersId { get; set; }
    
        public virtual AbnormalQuality AbnormalQuality { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ReceiveDetails ReceiptDetails { get; set; }
    }
}
