//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public System.Guid Id { get; set; }
        public System.Guid ProjectItemCostId { get; set; }
        public int Bidders { get; set; }
        public int NumberTenders { get; set; }
        public string ItemName { get; set; }
        public System.Guid ShopFlowId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
    }
}
