//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProcessingAtlasId { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> ManufacturersId { get; set; }
        public string FactoryNumber { get; set; }
        public System.Guid MaterialCategoriesId { get; set; }
        public Nullable<decimal> UnitWeight { get; set; }
        public Nullable<int> OrderLength { get; set; }
        public Nullable<decimal> RequiredQuantity { get; set; }
        public Nullable<decimal> RequiredQuantitySubtotal { get; set; }
        public decimal RequiredQuantityWeightSummary { get; set; }
        public Nullable<decimal> NumberofOrdersNotPlaced { get; set; }
        public Nullable<decimal> QuantityofOrderSummary { get; set; }
        public Nullable<decimal> PrepareSubtotal { get; set; }
        public Nullable<decimal> TotalWeightofOrder { get; set; }
        public Nullable<decimal> ArrivalCondition_QuantitySubtotal { get; set; }
        public Nullable<decimal> ArrivalCondition_WeightSubtotal { get; set; }
        public Nullable<decimal> ArrivalCondition_OutofStock { get; set; }
        public Nullable<decimal> ReturnStatus_QuantitySubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_WeightSubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Receipt_QuantitySubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Receipt_WeightSubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Charge_QuantitySubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Charge_WeightSubtotal { get; set; }
        public Nullable<decimal> PickingCondition_QuantitySubtotal { get; set; }
        public Nullable<decimal> PickingCondition_WeightSubtotal { get; set; }
        public Nullable<decimal> InventoryMargin_LossAdjustment_QuantitySubtotal { get; set; }
        public Nullable<decimal> InventoryMargin_LossAdjustment_WeightSubtotal { get; set; }
        public Nullable<decimal> InventoryStatus_QuantitySubtotal { get; set; }
        public Nullable<decimal> InventoryStatus_WeightSubtotal { get; set; }
        public Nullable<System.Guid> PurchasingOrderId { get; set; }
        public string ProcessingNumber { get; set; }
        public string MaterialAndSurfaceTreatment { get; set; }
        public string Unit { get; set; }
        public Nullable<System.Guid> ShopFlowId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public string Size { get; set; }
    
        public virtual MaterialCategories MaterialCategories { get; set; }
        public virtual ProcessingAtlas ProcessingAtlas { get; set; }
        public virtual ShopFlow ShopFlow { get; set; }
        public virtual Users Users { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
