//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compositions
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> EngineeringId { get; set; }
        public int Order { get; set; }
        public Nullable<int> CompositionTypeId { get; set; }
        public string Code { get; set; }
        public string SpecDesc { get; set; }
        public float Amount { get; set; }
        public string Reserved1 { get; set; }
        public string Reserved2 { get; set; }
        public string Reserved3 { get; set; }
        public string Reserved4 { get; set; }
        public string Reserved5 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
    
        public virtual CompositionTypes CompositionTypes { get; set; }
        public virtual Engineering Engineering { get; set; }
    }
}
