//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionAtlas
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProjectContractId { get; set; }
        public string ImageName { get; set; }
        public int Edition { get; set; }
        public System.DateTime SubmissionDate { get; set; }
        public string SubmitCertificateNumber { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string ReplyNumber { get; set; }
        public int ReplyContent { get; set; }
        public bool Finalized { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
    
        public virtual Projects Projects { get; set; }
    }
}
