//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contacts()
        {
            this.Principal = new HashSet<Manufacturers>();
            this.MainContactPerson = new HashSet<Manufacturers>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Dep { get; set; }
        public string Title { get; set; }
        public string Phone { get; set; }
        public string ExtensionNumber { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public bool IsPrincipal { get; set; }
        public bool Void { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public string EMail { get; set; }
        public bool IsDefault { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufacturers> Principal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufacturers> MainContactPerson { get; set; }
    }
}
