//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlTableDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlTableDetails()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.OrderMaterialValuation = new HashSet<OrderMaterialValuation>();
            this.RequiredDetails = new HashSet<RequiredDetails>();
            this.Inventory = new HashSet<Inventory>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ControlTableId { get; set; }
        public Nullable<decimal> RequiredQuantitySubtotal { get; set; }
        public Nullable<decimal> RequiredQuantityWeightSummary { get; set; }
        public Nullable<decimal> NumberofOrdersNotPlaced { get; set; }
        public Nullable<decimal> QuantityofOrderSummary { get; set; }
        public Nullable<decimal> PrepareSubtotal { get; set; }
        public Nullable<decimal> TotalWeightofOrder { get; set; }
        public Nullable<decimal> ArrivalCondition_QuantitySubtotal { get; set; }
        public Nullable<decimal> ArrivalCondition_WeightSubtotal { get; set; }
        public Nullable<decimal> ArrivalCondition_OutofStock { get; set; }
        public Nullable<decimal> ReturnStatus_QuantitySubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_WeightSubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Receipt_QuantitySubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Receipt_WeightSubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Charge_QuantitySubtotal { get; set; }
        public Nullable<decimal> ReturnStatus_Charge_WeightSubtotal { get; set; }
        public Nullable<decimal> PickingCondition_QuantitySubtotal { get; set; }
        public Nullable<decimal> PickingCondition_WeightSubtotal { get; set; }
        public Nullable<decimal> InventoryMargin_LossAdjustment_QuantitySubtotal { get; set; }
        public Nullable<decimal> InventoryMargin_LossAdjustment_WeightSubtotal { get; set; }
        public Nullable<decimal> InventoryStatus_QuantitySubtotal { get; set; }
        public Nullable<decimal> InventoryStatus_WeightSubtotal { get; set; }
    
        public virtual ControlTables ControlTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMaterialValuation> OrderMaterialValuation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiredDetails> RequiredDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventory> Inventory { get; set; }
    }
}
