//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncodingRecords
    {
        public System.Guid Id { get; set; }
        public string EncodingName { get; set; }
        public string CodeName1 { get; set; }
        public string CodeName2 { get; set; }
        public string CodeName3 { get; set; }
        public string CodeName4 { get; set; }
        public string CodeName5 { get; set; }
        public int Number1 { get; set; }
        public int Number2 { get; set; }
        public int Number3 { get; set; }
        public int Number4 { get; set; }
        public int Number5 { get; set; }
    }
}
