//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Engineering()
        {
            this.ShopFlowHistory = new HashSet<ShopFlowHistory>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ProjectId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShorName { get; set; }
        public float Area { get; set; }
        public System.DateTime WarrantyDate { get; set; }
        public string Architect { get; set; }
        public int BuildingHeightAboveground { get; set; }
        public int BuildingHeightUnderground { get; set; }
        public string BuildingCompany { get; set; }
        public string SupervisionUnit { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public bool IsAppend { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShopFlowHistory> ShopFlowHistory { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
