//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetails>();
            this.InvoiceDetails_Material = new HashSet<InvoiceDetails_Material>();
            this.InvoiceDetails_Miscellaneous = new HashSet<InvoiceDetails_Miscellaneous>();
        }
    
        public System.Guid Id { get; set; }
        public int Order { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.Guid> InvoiceManufacturerId { get; set; }
        public string ManufacturerInvoiceNumber { get; set; }
        public Nullable<System.Guid> InvoiceUserId { get; set; }
        public System.DateTime InvoiceTime { get; set; }
        public System.DateTime EstimatedPaymentDate { get; set; }
        public bool PrepaymentsOnly { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails_Material> InvoiceDetails_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails_Miscellaneous> InvoiceDetails_Miscellaneous { get; set; }
        public virtual Users CreateUser { get; set; }
        public virtual Users InvoiceUser { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
    }
}
