//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetails_Material
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> InvoiceId { get; set; }
        public Nullable<System.Guid> OrderMaterialValuationId { get; set; }
        public Nullable<System.Guid> ReceiptDetailsId { get; set; }
        public decimal UnitPrice { get; set; }
        public double Weight { get; set; }
        public decimal TotalPrice { get; set; }
        public int Quantity { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual OrderMaterialValuation OrderMaterialValuation { get; set; }
        public virtual ReceiveDetails ReceiptDetails { get; set; }
    }
}
