//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturersBussinessItems
    {
        public System.Guid Id { get; set; }
        public System.Guid MaterialCategoriesId { get; set; }
        public string Name { get; set; }
        public int TranscationId { get; set; }
        public byte PaymentTypeId { get; set; }
        public byte TicketTypeId { get; set; }
    
        public virtual MaterialCategories MaterialCategories { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual TicketTypes TicketTypes { get; set; }
    }
}
