//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufacturersBussinessItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManufacturersBussinessItems()
        {
            this.SupplierTranscationItem = new HashSet<SupplierTranscationItem>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> MaterialCategoriesId { get; set; }
        public string Name { get; set; }
        public Nullable<byte> PaymentTypeId { get; set; }
        public Nullable<int> TicketPeriodId { get; set; }
        public Nullable<System.Guid> ManufacturersId { get; set; }
        public Nullable<int> TranscationCategoriesId { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MaterialCategories MaterialCategories { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
        public virtual TicketPeriod TicketPeriod { get; set; }
        public virtual TranscationCategories TranscationCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierTranscationItem> SupplierTranscationItem { get; set; }
    }
}
