//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialValuation
    {
        public System.Guid Id { get; set; }
        public System.Guid FormDetailId { get; set; }
        public string ItemName { get; set; }
        public string Material { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> TotalPrice { get; set; }
    
        public virtual FormDetails FormDetails { get; set; }
    }
}
