//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Molds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Molds()
        {
            this.ProjectMolds = new HashSet<MoldsInProjects>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTime OpenDate { get; set; }
        public string LegendMoldReduction { get; set; }
        public string UsePosition { get; set; }
        public string Code { get; set; }
        public System.Guid ManufacturersId { get; set; }
        public System.Guid MaterialId { get; set; }
        public float UnitWeight { get; set; }
        public string SurfaceTreatment { get; set; }
        public float PaintArea { get; set; }
        public float MembraneTreatment { get; set; }
        public float MinimumYield { get; set; }
        public float ProductionIngot { get; set; }
        public float TotalOrderWeight { get; set; }
        public int MoldUseStatusId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual MoldUseStatus MoldUseStatus { get; set; }
        public virtual Users CreateUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoldsInProjects> ProjectMolds { get; set; }
    }
}
