//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaterialValuation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderMaterialValuation()
        {
            this.InvoiceDetails_Material = new HashSet<InvoiceDetails_Material>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> ControlTableDetailId { get; set; }
        public double Weight { get; set; }
        public int TotalPrice { get; set; }
        public Nullable<System.Guid> RequiredDetailsId { get; set; }
    
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetails_Material> InvoiceDetails_Material { get; set; }
        public virtual ControlTableDetails ControlTableDetails { get; set; }
        public virtual RequiredDetails RequiredDetails { get; set; }
    }
}
