//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderControlTableDetails
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProcessingAtlasId { get; set; }
        public Nullable<System.Guid> ControlTableDetailsId { get; set; }
        public Nullable<System.Guid> OrderDetailId { get; set; }
        public int OrderTotalQuantity { get; set; }
        public decimal OrderTotalWeight { get; set; }
    
        public virtual ControlTableDetails ControlTableDetails { get; set; }
        public virtual OrderDetails OrderDetails { get; set; }
        public virtual ProcessingAtlas ProcessingAtlas { get; set; }
    }
}
