//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.OrderMaterialValuation = new HashSet<OrderMaterialValuation>();
            this.OrderMiscellaneous = new HashSet<OrderMiscellaneous>();
            this.Returns = new HashSet<Returns>();
            this.PickList = new HashSet<PickList>();
        }
    
        public System.Guid Id { get; set; }
        public int Order { get; set; }
        public Nullable<System.Guid> OrderTypeId { get; set; }
        public string RequiredDep { get; set; }
        public string FormNumber { get; set; }
        public string BatchNumber { get; set; }
        public System.DateTime ExpectedDelivery { get; set; }
        public Nullable<System.DateTime> ActualDelivery { get; set; }
        public Nullable<System.Guid> MakingUserId { get; set; }
        public Nullable<System.DateTime> MakingTime { get; set; }
        public Nullable<double> ReservedPercentage { get; set; }
        public Nullable<System.Guid> ShippingManufactureId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMaterialValuation> OrderMaterialValuation { get; set; }
        public virtual Users CreateUsers { get; set; }
        public virtual Users MakingUsers { get; set; }
        public virtual OrderTypes OrderTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMiscellaneous> OrderMiscellaneous { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickList> PickList { get; set; }
    }
}
