//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.Clients = new HashSet<Manufacturers>();
            this.ProjectContract = new HashSet<ProjectContract>();
        }
    
        public System.Guid Id { get; set; }
        public string Code { get; set; }
        public string ProjectName { get; set; }
        public string ShortName { get; set; }
        public System.DateTime ProjectSigningDate { get; set; }
        public string SiteAddress { get; set; }
        public System.Guid ClientId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public string Comment { get; set; }
        public bool Void { get; set; }
        public byte State { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> WarrantyDate { get; set; }
        public string Architect { get; set; }
        public Nullable<int> BuildingHeightAboveground { get; set; }
        public Nullable<int> BuildingHeightUnderground { get; set; }
        public string BuildingCompany { get; set; }
        public string SupervisionUnit { get; set; }
        public Nullable<float> Area { get; set; }
        public Nullable<byte> PaymentType { get; set; }
        public Nullable<byte> CheckoutDay { get; set; }
        public Nullable<byte> PaymentDay { get; set; }
    
        public virtual States States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manufacturers> Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectContract> ProjectContract { get; set; }
    }
}
