//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Required
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Required()
        {
            this.RequiredDetails = new HashSet<RequiredDetails>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ProjectId { get; set; }
        public Nullable<System.Guid> ProjectContractId { get; set; }
        public string FormNumber { get; set; }
        public Nullable<System.Guid> ManufacturersId { get; set; }
        public Nullable<System.Guid> MaterialCategoriesId { get; set; }
        public System.DateTime MakingTime { get; set; }
        public System.Guid MakingUserId { get; set; }
        public string RequiredPostion { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public Nullable<System.Guid> ShopFlowId { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual MaterialCategories MaterialCategories { get; set; }
        public virtual ProjectContract ProjectContract { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Users CreateUser { get; set; }
        public virtual Users MakingUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiredDetails> RequiredDetails { get; set; }
        public virtual ShopFlow ShopFlow { get; set; }
    }
}
