//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Returns()
        {
            this.ReturnDetails = new HashSet<ReturnDetails>();
        }
    
        public System.Guid Id { get; set; }
        public int Order { get; set; }
        public string ReturnNumber { get; set; }
        public Nullable<System.Guid> IncomingManufacturerId { get; set; }
        public string IncomingNumber { get; set; }
        public Nullable<System.Guid> MakingUserId { get; set; }
        public System.DateTime MakingTime { get; set; }
        public string MakerPhone { get; set; }
        public Nullable<System.Guid> StockId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CreateUserId { get; set; }
        public string ReceiptNumber { get; set; }
    
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnDetails> ReturnDetails { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Stocks Stocks { get; set; }
    }
}
