//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierTranscationItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierTranscationItem()
        {
            this.AbnormalQuality = new HashSet<AbnormalQuality>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ManufacturersBussinessItemsId { get; set; }
        public System.Guid ProjectId { get; set; }
        public string PlaceofReceipt { get; set; }
        public string SiteContactPerson { get; set; }
        public string SiteContactPersonPhone { get; set; }
        public Nullable<System.Guid> NextManufacturersId { get; set; }
    
        public virtual ManufacturersBussinessItems ManufacturersBussinessItems { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Manufacturers NextManufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbnormalQuality> AbnormalQuality { get; set; }
    }
}
