//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Shipping
    {
        public string PickListNumber { get; set; }
        public string BatchNumber { get; set; }
        public string RequiredDetailsCode { get; set; }
        public string ManufacturersCode { get; set; }
        public string ManufacturersName { get; set; }
        public string MaterialsName { get; set; }
        public decimal UnitWeight { get; set; }
        public Nullable<int> OrderLength { get; set; }
        public decimal OrderQuantity { get; set; }
        public int ShippingOrder { get; set; }
        public double Weight { get; set; }
        public int LackQuantity { get; set; }
        public int ShippingQuantity { get; set; }
        public string Comment { get; set; }
        public Nullable<System.Guid> PickListId { get; set; }
        public Nullable<System.Guid> OrderDetailId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> RequiredDetailsId { get; set; }
        public Nullable<System.Guid> ShippingManufactureId { get; set; }
        public Nullable<System.Guid> MaterialsId { get; set; }
    }
}
