//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderControlTable
    {
        public string FormNumber { get; set; }
        public string Code { get; set; }
        public string ProjectsName { get; set; }
        public string RequiredDetailsCode { get; set; }
        public string ManufacturersCode { get; set; }
        public string ManufacturersName { get; set; }
        public string MaterialsName { get; set; }
        public decimal UnitWeight { get; set; }
        public Nullable<int> OrderLength { get; set; }
        public Nullable<decimal> OrderQuantity { get; set; }
        public Nullable<decimal> SparePartsNumber { get; set; }
        public Nullable<decimal> OrderTotalQuantity { get; set; }
        public Nullable<decimal> OrderTotalWeight { get; set; }
        public System.DateTime ExpectedDelivery { get; set; }
        public Nullable<int> ShippingOrder { get; set; }
        public string Comment { get; set; }
        public int LackQuantity { get; set; }
        public Nullable<decimal> LackWeight { get; set; }
        public Nullable<int> Atlas { get; set; }
        public string ReceiptNumber { get; set; }
        public System.Guid OrdersMakingUserId { get; set; }
        public System.Guid OrderTypeId { get; set; }
        public System.Guid ShippingManufactureId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public System.Guid ControlTableDetailId { get; set; }
        public System.Guid RequiredDetailsId { get; set; }
        public System.Guid MaterialsId { get; set; }
        public System.Guid RequiredId { get; set; }
        public System.Guid OrderDetailId { get; set; }
        public System.Guid ReceiptsId { get; set; }
        public System.Guid ProjectId { get; set; }
        public System.Guid ProjectContractId { get; set; }
    }
}
