//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ObtainMaterial
    {
        public string RequiredDetailsCode { get; set; }
        public string ManufacturersCode { get; set; }
        public string ManufacturersName { get; set; }
        public string MaterialsName { get; set; }
        public decimal UnitWeight { get; set; }
        public Nullable<int> OrderLength { get; set; }
        public int ShippingQuantity { get; set; }
        public Nullable<decimal> InventoryStatus_QuantitySubtotal { get; set; }
        public string Comment { get; set; }
        public Nullable<int> PickingStatus_QuantitySubtotal { get; set; }
        public Nullable<double> PickingStatus_WeightSubtotal { get; set; }
        public System.Guid PickListDetailsId { get; set; }
        public System.Guid PickListId { get; set; }
        public System.Guid OrderDetailsId { get; set; }
        public System.Guid RequiredDetailsId { get; set; }
        public System.Guid RequiredId { get; set; }
        public System.Guid ManufacturersId { get; set; }
        public System.Guid ControlTableDetailsId { get; set; }
    }
}
