//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderMaterialValuation
    {
        public System.Guid ProjectId { get; set; }
        public System.Guid OrdersId { get; set; }
        public System.Guid ShopFlowId { get; set; }
        public Nullable<System.Guid> OrderTypeId { get; set; }
        public System.Guid OrderMaterialValuationId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string FormName { get; set; }
        public string ShowFlowName { get; set; }
        public string RequiredDep { get; set; }
        public string FormNumber { get; set; }
        public string BatchNumber { get; set; }
        public System.DateTime ExpectedDelivery { get; set; }
        public Nullable<System.DateTime> ActualDelivery { get; set; }
        public string MakerUser { get; set; }
        public Nullable<System.DateTime> MakingTime { get; set; }
        public Nullable<double> ReservedPercentage { get; set; }
        public string ShippingManufacture { get; set; }
        public Nullable<System.Guid> ShippingManufactureId { get; set; }
        public Nullable<System.Guid> MaterialsId { get; set; }
        public string Materials { get; set; }
        public float UnitPrice { get; set; }
        public double Weight { get; set; }
        public int TotalPrice { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
    }
}
