//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Orders
    {
        public System.Guid ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string ShopFlowName { get; set; }
        public Nullable<System.Guid> OrderTypeId { get; set; }
        public string FormName { get; set; }
        public System.Guid RequiredId { get; set; }
        public string FormNumber { get; set; }
        public string Code { get; set; }
        public string FactoryNumber { get; set; }
        public System.Guid MaterialsId { get; set; }
        public string Materials { get; set; }
        public decimal UnitWeight { get; set; }
        public Nullable<int> OrderLength { get; set; }
        public decimal RequiredQuantity { get; set; }
        public decimal SparePartsNumber { get; set; }
        public decimal OrderQuantity { get; set; }
        public string Comment { get; set; }
    }
}
