//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokiku.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ShippingList
    {
        public string Name { get; set; }
        public string ShippingNumber { get; set; }
        public string ReceiptNumber { get; set; }
        public string PickListNumber { get; set; }
        public System.DateTime PickListTime { get; set; }
        public System.DateTime ShippingTime { get; set; }
        public string ShippingName { get; set; }
        public System.Guid OrderDetailsId { get; set; }
        public System.Guid PickListDetailsId { get; set; }
        public System.Guid ReceiptDetailsId { get; set; }
        public System.Guid PickListId { get; set; }
        public System.Guid ShippingId { get; set; }
        public System.Guid ReceiptsId { get; set; }
    }
}
